### ISSUE TITLE
It's probably not a good idea to store a list of products client side

### ISSUE THREAD

**Issue by Razpudding** [Djaygo/real-time-web#5]
Wouldn't it make more sense if the server just told a new client which products there are? Then you would create the relevent images for it. That way you can centralize control over the products and even add a new product server side and have it show up on OLD clients!

**Comment by Djaygo** [comment]
Created the following function which reads all the files in the given folder path (images). Creates a an array of object with image id and path, this array goes into the index.pug template.

By doing this i can add more png's to the folder which automatically be put on the website.

```javascript
//  Create array with image objects from the given folder
function createAvailableProductsArray(folderPath) {
  var files = fs.readdirSync(folderPath);
  let products = [];
  files.map(image => {
    let imageInfo = {};
    imageInfo['id'] = image.split('.')[0];
    imageInfo['path'] =`../images/${image}`;
    products.push(imageInfo);
  });
  return products;
}
```
